name: Build Personalizado do Brave Browser

# Gatilhos: aciona o workflow em pushes para a branch 'main'
# ou manualmente através da aba Actions no GitHub (workflow_dispatch)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Use um runner do Ubuntu. Para builds reais, um self-hosted runner é recomendado.
    # Ex: runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do seu código e submódulos
      # O Brave depende muito de submódulos (como o código do Chromium)
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 2. Instalação de Dependências do Sistema
      # Com base nas instruções oficiais de build do Brave para Linux.
      - name: Instalar Dependências do Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang libdbus-1-dev libatk-bridge2.0-dev \
          libgtk-3-dev libcups2-dev libxss-dev libnss3-dev libasound2-dev \
          libxtst-dev curl git python3 npm

      # 3. Configuração do Ambiente Brave
      # O Brave usa scripts para baixar o toolchain do Chromium e outras dependências
      - name: Sincronizar Dependências e Configurar gclient
        run: |
          npm install
          npm run-script sync

      # 4. Compilação do Brave
      # Este é o passo mais demorado.
      # A flag '--debug' cria uma build de depuração (mais rápida, maior).
      # Remova-a para uma build de release (mais lenta, otimizada).
      - name: Compilar o Navegador Brave
        run: |
          npm run build -- --debug # Remova --debug para uma build de Release

      # 5. Fazer Upload do Artefato
      # Pega o resultado da compilação e o disponibiliza para download.
      - name: Upload do Artefato da Build
        uses: actions/upload-artifact@v4
        with:
          name: brave-browser-linux-x64
          # O caminho exato pode variar. Verifique a saída da compilação.
          # Geralmente fica em src/out/Brave-Debug ou src/out/Release
          path: src/out/Brave-Debug/
