name: Brave Lite Build (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Checkout brave-browser repo
      uses: actions/checkout@v4

    - name: Setup depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git depot_tools
        echo "${{ runner.temp }}\\depot_tools" >> $env:GITHUB_PATH

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install npm deps
      run: npm install

    - name: Sync dependencies with gclient
      run: gclient sync --with_branch_heads --with_tags
      working-directory: src

    - name: Apply patch brave-lite-final
      run: git apply ../../patches/brave-lite-final.patch
      working-directory: src/brave

    - name: Configure build with GN
      run: |
        echo 'is_debug = false
        is_official_build = true
        target_os = "win"
        target_cpu = "x64"
        brave_channel = "stable"
        enable_brave_rewards = false
        enable_brave_news = false
        enable_brave_ads = false
        enable_brave_vpn = false
        enable_brave_wallet = false
        enable_brave_talk = false
        enable_brave_ai_chat = false
        enable_brave_tor = false
        enable_brave_referrals = false
        enable_brave_telemetry = false
        enable_brave_reporting = false' > args.gn

        gn gen out/Default --args="`type args.gn`"
      working-directory: src

    - name: Build Brave Lite
      run: autoninja -C out/Default brave
      working-directory: src

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: brave-lite-windows
        path: src/out/Default/brave.exe
